#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace BeerLike.PackageDeployer.Models.Dataverse
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="BeerLike.PackageDeployer.Models.Dataverse.FieldSecurityProfile"/> entities.
		/// </summary>
		public System.Linq.IQueryable<BeerLike.PackageDeployer.Models.Dataverse.FieldSecurityProfile> FieldSecurityProfileSet
		{
			get
			{
				return this.CreateQuery<BeerLike.PackageDeployer.Models.Dataverse.FieldSecurityProfile>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="BeerLike.PackageDeployer.Models.Dataverse.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<BeerLike.PackageDeployer.Models.Dataverse.Role> RoleSet
		{
			get
			{
				return this.CreateQuery<BeerLike.PackageDeployer.Models.Dataverse.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="BeerLike.PackageDeployer.Models.Dataverse.Team"/> entities.
		/// </summary>
		public System.Linq.IQueryable<BeerLike.PackageDeployer.Models.Dataverse.Team> TeamSet
		{
			get
			{
				return this.CreateQuery<BeerLike.PackageDeployer.Models.Dataverse.Team>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="BeerLike.PackageDeployer.Models.Dataverse.TeamProfiles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<BeerLike.PackageDeployer.Models.Dataverse.TeamProfiles> TeamProfilesSet
		{
			get
			{
				return this.CreateQuery<BeerLike.PackageDeployer.Models.Dataverse.TeamProfiles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="BeerLike.PackageDeployer.Models.Dataverse.TeamRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<BeerLike.PackageDeployer.Models.Dataverse.TeamRoles> TeamRolesSet
		{
			get
			{
				return this.CreateQuery<BeerLike.PackageDeployer.Models.Dataverse.TeamRoles>();
			}
		}
	}
}
#pragma warning restore CS1591
