#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerLike.PackageDeployer.Models.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("teamroles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class TeamRoles : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the teamroles entity
		/// </summary>
		public partial class Fields
		{
			public const string RoleId = "roleid";
			public const string TeamId = "teamid";
			public const string TeamRoleId = "teamroleid";
			public const string Id = "teamroleid";
			public const string VersionNumber = "versionnumber";
			public const string teamroles_association = "teamroles_association";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public TeamRoles() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "teamroles";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "teamrolescollection";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("roleid")]
		public System.Nullable<System.Guid> RoleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("roleid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamid")]
		public System.Nullable<System.Guid> TeamId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("teamid");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamroleid")]
		public System.Nullable<System.Guid> TeamRoleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("teamroleid");
			}
			set
			{
				this.OnPropertyChanging("TeamRoleId");
				this.SetAttributeValue("teamroleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("TeamRoleId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamroleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.TeamRoleId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N teamroles_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("teamroles_association")]
		public System.Collections.Generic.IEnumerable<BeerLike.PackageDeployer.Models.Dataverse.Team> teamroles_association
		{
			get
			{
				return this.GetRelatedEntities<BeerLike.PackageDeployer.Models.Dataverse.Team>("teamroles_association", null);
			}
			set
			{
				this.OnPropertyChanging("teamroles_association");
				this.SetRelatedEntities<BeerLike.PackageDeployer.Models.Dataverse.Team>("teamroles_association", null, value);
				this.OnPropertyChanged("teamroles_association");
			}
		}
	}
}
#pragma warning restore CS1591
